version: 1.2.{build}
image: Visual Studio 2026
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- cmd: dotnet restore source\YouShouldSpellcheck.Analyzer.sln
build:
  project: source\YouShouldSpellcheck.Analyzer.sln
  verbosity: minimal
after_build:
- cmd: dotnet pack source\YouShouldSpellcheck.Analyzer\YouShouldSpellcheck.Analyzer.csproj --configuration %CONFIGURATION% --no-build --no-restore -p:PackageVersion=%APPVEYOR_BUILD_VERSION%
artifacts:
- path: artifacts\packages\*.nupkg
  type: NuGetPackage
